<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VerbsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('verbs')->insert(['first_form' => 'abide', 'second_form' => 'abode; abided', 'third_form' => 'abode; abided', 'translate' => 'пребывать; держаться']);
        DB::table('verbs')->insert(['first_form' => 'arise', 'second_form' => 'arose', 'third_form' => 'arisen', 'translate' => 'подняться; возникнуть']);
        DB::table('verbs')->insert(['first_form' => 'awake', 'second_form' => 'awoke', 'third_form' => 'awaked; awoke', 'translate' => 'будить; проснуться']);
        DB::table('verbs')->insert(['first_form' => 'backbite', 'second_form' => 'backbitten', 'third_form' => 'backbitten', 'translate' => 'клеветать']);
        DB::table('verbs')->insert(['first_form' => 'backslide', 'second_form' => 'backslid', 'third_form' => 'backslid', 'translate' => 'отпадать']);
        DB::table('verbs')->insert(['first_form' => 'be', 'second_form' => 'was; were', 'third_form' => 'been', 'translate' => 'быть; нести; родить']);
        DB::table('verbs')->insert(['first_form' => 'bear', 'second_form' => 'bore', 'third_form' => 'born; borne', 'translate' => 'родить']);
        DB::table('verbs')->insert(['first_form' => 'beat', 'second_form' => 'beat', 'third_form' => 'beaten', 'translate' => 'бить']);
        DB::table('verbs')->insert(['first_form' => 'become', 'second_form' => 'became', 'third_form' => 'become', 'translate' => 'стать; сделаться']);
        DB::table('verbs')->insert(['first_form' => 'befall', 'second_form' => 'befell', 'third_form' => 'befallen', 'translate' => 'случиться']);
        DB::table('verbs')->insert(['first_form' => 'beget', 'second_form' => 'begot; begat', 'third_form' => 'begotten', 'translate' => 'порождать']);
        DB::table('verbs')->insert(['first_form' => 'begin', 'second_form' => 'began', 'third_form' => 'begun', 'translate' => 'начать']);
        DB::table('verbs')->insert(['first_form' => 'begird', 'second_form' => 'begirt', 'third_form' => 'begirt', 'translate' => 'опоясывать']);
        DB::table('verbs')->insert(['first_form' => 'behold', 'second_form' => 'beheld', 'third_form' => 'beheld', 'translate' => 'зреть']);
        DB::table('verbs')->insert(['first_form' => 'bend', 'second_form' => 'bent', 'third_form' => 'bent; bended', 'translate' => 'согнуть(ся)']);
        DB::table('verbs')->insert(['first_form' => 'bereave', 'second_form' => 'bereft; bereaved', 'third_form' => 'bereft; bereaved', 'translate' => 'лишать']);
        DB::table('verbs')->insert(['first_form' => 'beseech', 'second_form' => 'besought; beseeched', 'third_form' => 'besought; beseeched', 'translate' => 'умолять; упрашивать']);
        DB::table('verbs')->insert(['first_form' => 'beset', 'second_form' => 'beset', 'third_form' => 'beset', 'translate' => 'осаждать']);
        DB::table('verbs')->insert(['first_form' => 'bespeak', 'second_form' => 'bespoke', 'third_form' => 'bespoke; bespoken', 'translate' => 'заказывать']);
        DB::table('verbs')->insert(['first_form' => 'bespit', 'second_form' => 'bespat', 'third_form' => 'bespat', 'translate' => 'заплевывать']);
        DB::table('verbs')->insert(['first_form' => 'bestride', 'second_form' => 'bestrode', 'third_form' => 'bestridden', 'translate' => 'садиться; сидеть верхом']);
        DB::table('verbs')->insert(['first_form' => 'bet', 'second_form' => 'bet; betted', 'third_form' => 'bet; betted', 'translate' => 'держать пари']);
        DB::table('verbs')->insert(['first_form' => 'betake', 'second_form' => 'betook', 'third_form' => 'betaken', 'translate' => 'приниматься; отправляться']);
        DB::table('verbs')->insert(['first_form' => 'bid', 'second_form' => 'bad; bade; bid', 'third_form' => 'bid; bidden', 'translate' => 'велеть; просить']);
        DB::table('verbs')->insert(['first_form' => 'bind', 'second_form' => 'bound', 'third_form' => 'bound', 'translate' => 'связать']);
        DB::table('verbs')->insert(['first_form' => 'bite', 'second_form' => 'bit', 'third_form' => 'bit; bitten', 'translate' => 'кусать']);
        DB::table('verbs')->insert(['first_form' => 'bleed', 'second_form' => 'bled', 'third_form' => 'bled', 'translate' => 'кровоточить']);
        DB::table('verbs')->insert(['first_form' => 'bless', 'second_form' => 'blessed', 'third_form' => 'blessed; blest', 'translate' => 'благословлять']);
        DB::table('verbs')->insert(['first_form' => 'blow', 'second_form' => 'blew', 'third_form' => 'blown; blowed', 'translate' => 'дуть']);
        DB::table('verbs')->insert(['first_form' => 'break', 'second_form' => 'broke', 'third_form' => 'broken', 'translate' => '(с)ломать']);
        DB::table('verbs')->insert(['first_form' => 'breed', 'second_form' => 'bred', 'third_form' => 'bred', 'translate' => 'выращивать']);
        DB::table('verbs')->insert(['first_form' => 'bring', 'second_form' => 'brought', 'third_form' => 'brought', 'translate' => 'принести']);
        DB::table('verbs')->insert(['first_form' => 'broadcast', 'second_form' => 'broadcast', 'third_form' => 'broadcast', 'translate' => 'распространять; разбрасывать']);
        DB::table('verbs')->insert(['first_form' => 'browbeat', 'second_form' => 'browbeat', 'third_form' => 'browbeaten', 'translate' => 'запугивать']);
        DB::table('verbs')->insert(['first_form' => 'build', 'second_form' => 'built', 'third_form' => 'built', 'translate' => 'строить']);
        DB::table('verbs')->insert(['first_form' => 'burn', 'second_form' => 'burnt; burned', 'third_form' => 'burnt; burned', 'translate' => 'жечь; гореть']);
        DB::table('verbs')->insert(['first_form' => 'burst', 'second_form' => 'burst', 'third_form' => 'burst', 'translate' => 'разразиться; взорваться']);
        DB::table('verbs')->insert(['first_form' => 'bust', 'second_form' => 'bust; busted', 'third_form' => 'bust; busted', 'translate' => 'разжаловать']);
        DB::table('verbs')->insert(['first_form' => 'buy', 'second_form' => 'bought', 'third_form' => 'bought', 'translate' => 'купить']);
        DB::table('verbs')->insert(['first_form' => 'can', 'second_form' => 'could', 'third_form' => '- / been able', 'translate' => 'мочь; уметь']);
        DB::table('verbs')->insert(['first_form' => 'cast', 'second_form' => 'cast', 'third_form' => 'cast', 'translate' => 'кинуть; лить металл']);
        DB::table('verbs')->insert(['first_form' => 'catch', 'second_form' => 'caught', 'third_form' => 'caught', 'translate' => 'ловить; поймать']);
        DB::table('verbs')->insert(['first_form' => 'chide', 'second_form' => 'chid; chided', 'third_form' => 'chid; chided; chidden', 'translate' => 'бранить']);
        DB::table('verbs')->insert(['first_form' => 'choose', 'second_form' => 'chose', 'third_form' => 'chosen', 'translate' => 'выбрать']);
        DB::table('verbs')->insert(['first_form' => 'cleave', 'second_form' => 'clove; cleft; cleaved', 'third_form' => 'cloven; cleft; cleaved', 'translate' => 'рассечь']);
        DB::table('verbs')->insert(['first_form' => 'cling', 'second_form' => 'clung', 'third_form' => 'clung', 'translate' => 'цепляться; льнуть']);
        DB::table('verbs')->insert(['first_form' => 'come', 'second_form' => 'came', 'third_form' => 'come', 'translate' => 'прийти']);
        DB::table('verbs')->insert(['first_form' => 'cost', 'second_form' => 'cost', 'third_form' => 'cost', 'translate' => 'стоить']);
        DB::table('verbs')->insert(['first_form' => 'countersink', 'second_form' => 'countersank', 'third_form' => 'countersunk', 'translate' => 'зенковать']);
        DB::table('verbs')->insert(['first_form' => 'creep', 'second_form' => 'crept', 'third_form' => 'crept', 'translate' => 'ползти']);
        DB::table('verbs')->insert(['first_form' => 'crow', 'second_form' => 'crowed; crew', 'third_form' => 'crowed', 'translate' => 'петь (о петухе)']);
        DB::table('verbs')->insert(['first_form' => 'cut', 'second_form' => 'cut', 'third_form' => 'cut', 'translate' => 'резать']);
        DB::table('verbs')->insert(['first_form' => 'dare', 'second_form' => 'durst; dared', 'third_form' => 'dared', 'translate' => 'сметь']);
        DB::table('verbs')->insert(['first_form' => 'deal', 'second_form' => 'dealt', 'third_form' => 'dealt', 'translate' => 'иметь дело']);
        DB::table('verbs')->insert(['first_form' => 'dig', 'second_form' => 'dug', 'third_form' => 'dug', 'translate' => 'копать']);
        DB::table('verbs')->insert(['first_form' => 'dive', 'second_form' => 'dived; dove', 'third_form' => 'dived', 'translate' => 'нырять; погружаться']);
        DB::table('verbs')->insert(['first_form' => 'do', 'second_form' => 'did', 'third_form' => 'done', 'translate' => 'делать', 'transcription' => "du:",
            'first_form_example_single' => "He does exercises every morning",
            'first_form_example_multiple' => "We usually do our homework",
            'first_form_example_negative' => "She doesn't do a job every day",
            'second_form_example_single' => "He did exercises yesterday morning",
            'second_form_example_multiple' => "We did our homework last weekend",
            'second_form_example_negative' => "She didn't do a job last month",
            'third_form_example_single' => "He has already done exercises",
            'third_form_example_multiple' => "We have already done our homework yet",
            'third_form_example_negative' => "She hasn't already done a job"
            ]);
        DB::table('verbs')->insert(['first_form' => 'draw', 'second_form' => 'drew', 'third_form' => 'drawn', 'translate' => 'тащить; рисовать']);
        DB::table('verbs')->insert(['first_form' => 'dream', 'second_form' => 'dreamt; dreamed', 'third_form' => 'dreamt; dreamed', 'translate' => 'грезить; мечтать']);
        DB::table('verbs')->insert(['first_form' => 'drink', 'second_form' => 'drank', 'third_form' => 'drunk', 'translate' => 'пить; выпить']);
        DB::table('verbs')->insert(['first_form' => 'drive', 'second_form' => 'drove', 'third_form' => 'driven', 'translate' => 'гнать; ехать']);
        DB::table('verbs')->insert(['first_form' => 'dwell', 'second_form' => 'dwelt', 'third_form' => 'dwelt', 'translate' => 'обитать; задерживаться']);
        DB::table('verbs')->insert(['first_form' => 'eat', 'second_form' => 'ate', 'third_form' => 'eaten', 'translate' => 'кушать; есть']);
        DB::table('verbs')->insert(['first_form' => 'fall', 'second_form' => 'fell', 'third_form' => 'fallen', 'translate' => 'падать']);
        DB::table('verbs')->insert(['first_form' => 'feed', 'second_form' => 'fed', 'third_form' => 'fed', 'translate' => 'кормить']);
        DB::table('verbs')->insert(['first_form' => 'feel', 'second_form' => 'felt', 'third_form' => 'felt', 'translate' => 'чувствовать']);
        DB::table('verbs')->insert(['first_form' => 'fight', 'second_form' => 'fought', 'third_form' => 'fought', 'translate' => 'сражаться']);
        DB::table('verbs')->insert(['first_form' => 'find', 'second_form' => 'found', 'third_form' => 'found', 'translate' => 'находить']);
        DB::table('verbs')->insert(['first_form' => 'flee', 'second_form' => 'fled', 'third_form' => 'fled', 'translate' => 'бежать; спасаться']);
        DB::table('verbs')->insert(['first_form' => 'fling', 'second_form' => 'flung', 'third_form' => 'flung', 'translate' => 'бросить']);
        DB::table('verbs')->insert(['first_form' => 'floodlight', 'second_form' => 'floodlighted; floodlit', 'third_form' => 'floodlighted; floodlit', 'translate' => 'освещать прожектором']);
        DB::table('verbs')->insert(['first_form' => 'fly', 'second_form' => 'flew', 'third_form' => 'flown', 'translate' => 'летать']);
        DB::table('verbs')->insert(['first_form' => 'forbear', 'second_form' => 'forbore', 'third_form' => 'forborne', 'translate' => 'воздерживаться']);
        DB::table('verbs')->insert(['first_form' => 'forbid', 'second_form' => 'forbad; forbade', 'third_form' => 'forbidden', 'translate' => 'запретить']);
        DB::table('verbs')->insert(['first_form' => 'forecast', 'second_form' => 'forecast; forecasted', 'third_form' => 'forecast; forecasted', 'translate' => 'предсказывать']);
        DB::table('verbs')->insert(['first_form' => 'foresee', 'second_form' => 'foresaw', 'third_form' => 'foreseen', 'translate' => 'предвидеть']);
        DB::table('verbs')->insert(['first_form' => 'foretell', 'second_form' => 'foretold', 'third_form' => 'foretold', 'translate' => 'предсказывать']);
        DB::table('verbs')->insert(['first_form' => 'forget', 'second_form' => 'forgot', 'third_form' => 'forgotten', 'translate' => 'забыть']);
        DB::table('verbs')->insert(['first_form' => 'forgive', 'second_form' => 'forgave', 'third_form' => 'forgiven', 'translate' => 'простить']);
        DB::table('verbs')->insert(['first_form' => 'forsake', 'second_form' => 'forsook', 'third_form' => 'forsaken', 'translate' => 'покидать']);
        DB::table('verbs')->insert(['first_form' => 'forswear', 'second_form' => 'forswore', 'third_form' => 'forsworn', 'translate' => 'отрекаться']);
        DB::table('verbs')->insert(['first_form' => 'freeze', 'second_form' => 'froze', 'third_form' => 'frozen', 'translate' => 'замерзнуть; замораживать']);
        DB::table('verbs')->insert(['first_form' => 'gainsay', 'second_form' => 'gainsaid', 'third_form' => 'gainsaid', 'translate' => 'отрицать; противоречить']);
        DB::table('verbs')->insert(['first_form' => 'get', 'second_form' => 'got', 'third_form' => 'got', 'translate' => 'получить']);
        DB::table('verbs')->insert(['first_form' => 'gild', 'second_form' => 'gilt; gilded', 'third_form' => 'gilt; gilded', 'translate' => 'позолотить']);
        DB::table('verbs')->insert(['first_form' => 'gird', 'second_form' => 'girded; girt', 'third_form' => 'girded; girt', 'translate' => 'опоясывать']);
        DB::table('verbs')->insert(['first_form' => 'give', 'second_form' => 'gave', 'third_form' => 'given', 'translate' => 'дать']);
        DB::table('verbs')->insert(['first_form' => 'go', 'second_form' => 'went', 'third_form' => 'gone', 'translate' => 'идти; уходить']);
        DB::table('verbs')->insert(['first_form' => 'grave', 'second_form' => 'graved', 'third_form' => 'graved; graven', 'translate' => 'гравировать']);
        DB::table('verbs')->insert(['first_form' => 'grind', 'second_form' => 'ground', 'third_form' => 'ground', 'translate' => 'точить; молоть']);
        DB::table('verbs')->insert(['first_form' => 'grow', 'second_form' => 'grew', 'third_form' => 'grown', 'translate' => 'расти']);
        DB::table('verbs')->insert(['first_form' => 'hamstring', 'second_form' => 'hamstringed; hamstrung', 'third_form' => 'hamstringed; hamstrung', 'translate' => 'подрезать поджилки']);
        DB::table('verbs')->insert(['first_form' => 'hang', 'second_form' => 'hung; hanged', 'third_form' => 'hung; hanged', 'translate' => 'висеть; повесить']);
        DB::table('verbs')->insert(['first_form' => 'have', 'second_form' => 'had', 'third_form' => 'had', 'translate' => 'иметь']);
        DB::table('verbs')->insert(['first_form' => 'hear', 'second_form' => 'heard', 'third_form' => 'heard', 'translate' => 'слушать']);
        DB::table('verbs')->insert(['first_form' => 'heave', 'second_form' => 'heaved; hove', 'third_form' => 'heaved; hove', 'translate' => 'подымать(ся)']);
        DB::table('verbs')->insert(['first_form' => 'hew', 'second_form' => 'hewed/td>', 'third_form' => 'hewed; hewn', 'translate' => 'рубить; тесать']);
        DB::table('verbs')->insert(['first_form' => 'hide', 'second_form' => 'hid', 'third_form' => 'hidden', 'translate' => 'прятать(ся)']);
        DB::table('verbs')->insert(['first_form' => 'hit', 'second_form' => 'hit', 'third_form' => 'hit', 'translate' => 'ударить; попасть']);
        DB::table('verbs')->insert(['first_form' => 'hold', 'second_form' => 'held', 'third_form' => 'held', 'translate' => 'держать']);
        DB::table('verbs')->insert(['first_form' => 'hurt', 'second_form' => 'hurt', 'third_form' => 'hurt', 'translate' => 'причинить боль']);
        DB::table('verbs')->insert(['first_form' => 'inlay', 'second_form' => 'inlaid', 'third_form' => 'inlaid', 'translate' => 'вкладывать; выстилать']);
        DB::table('verbs')->insert(['first_form' => 'input', 'second_form' => 'input; inputted', 'third_form' => 'input; inputted', 'translate' => 'входить']);
        DB::table('verbs')->insert(['first_form' => 'inset', 'second_form' => 'inset', 'third_form' => 'inset', 'translate' => 'вставлять; вкладывать']);
        DB::table('verbs')->insert(['first_form' => 'interweave', 'second_form' => 'interwove', 'third_form' => 'interwoven', 'translate' => 'воткать']);
        DB::table('verbs')->insert(['first_form' => 'keep', 'second_form' => 'kept', 'third_form' => 'kept', 'translate' => 'хранить']);
        DB::table('verbs')->insert(['first_form' => 'ken', 'second_form' => 'kenned; kent', 'third_form' => 'kenned', 'translate' => 'знать; узнавать по виду']);
        DB::table('verbs')->insert(['first_form' => 'kneel', 'second_form' => 'knelt; kneeled', 'third_form' => 'knelt; kneeled', 'translate' => 'становиться на колени']);
        DB::table('verbs')->insert(['first_form' => 'knit', 'second_form' => 'knit; knitted', 'third_form' => 'knit; knitted', 'translate' => 'вязать']);
        DB::table('verbs')->insert(['first_form' => 'know', 'second_form' => 'knew', 'third_form' => 'known', 'translate' => 'знать']);
        DB::table('verbs')->insert(['first_form' => 'lade', 'second_form' => 'laded', 'third_form' => 'laded; laden', 'translate' => 'грузить']);
        DB::table('verbs')->insert(['first_form' => 'lay', 'second_form' => 'laid', 'third_form' => 'laid', 'translate' => 'класть; положить']);
        DB::table('verbs')->insert(['first_form' => 'lead', 'second_form' => 'led', 'third_form' => 'led', 'translate' => 'вести']);
        DB::table('verbs')->insert(['first_form' => 'lean', 'second_form' => 'leant; leaned', 'third_form' => 'leant; leaned', 'translate' => 'опереться; прислониться']);
        DB::table('verbs')->insert(['first_form' => 'leap', 'second_form' => 'leapt; leaped', 'third_form' => 'leapt; leaped', 'translate' => 'прыгать']);
        DB::table('verbs')->insert(['first_form' => 'learn', 'second_form' => 'learnt; learned', 'third_form' => 'learnt; learned', 'translate' => 'учить']);
        DB::table('verbs')->insert(['first_form' => 'leave', 'second_form' => 'left', 'third_form' => 'left', 'translate' => 'оставить']);
        DB::table('verbs')->insert(['first_form' => 'lend', 'second_form' => 'lent', 'third_form' => 'lent', 'translate' => 'одолжить']);
        DB::table('verbs')->insert(['first_form' => 'let', 'second_form' => 'let', 'third_form' => 'let', 'translate' => 'пустить; дать']);
        DB::table('verbs')->insert(['first_form' => 'lie', 'second_form' => 'lay', 'third_form' => 'lain', 'translate' => 'лежать']);
        DB::table('verbs')->insert(['first_form' => 'light', 'second_form' => 'lit; lighted', 'third_form' => 'lit; lighted', 'translate' => 'осветить']);
        DB::table('verbs')->insert(['first_form' => 'lose', 'second_form' => 'lost', 'third_form' => 'lost', 'translate' => 'терять']);
        DB::table('verbs')->insert(['first_form' => 'make', 'second_form' => 'made', 'third_form' => 'made', 'translate' => 'делать']);
        DB::table('verbs')->insert(['first_form' => 'may', 'second_form' => 'might', 'third_form' => 'might', 'translate' => 'мочь; иметь возможность']);
        DB::table('verbs')->insert(['first_form' => 'mean', 'second_form' => 'meant', 'third_form' => 'meant', 'translate' => 'подразумевать']);
        DB::table('verbs')->insert(['first_form' => 'meet', 'second_form' => 'met', 'third_form' => 'met', 'translate' => 'встретить']);
        DB::table('verbs')->insert(['first_form' => 'miscast', 'second_form' => 'miscast', 'third_form' => 'miscast', 'translate' => 'неправильно распределять роли']);
        DB::table('verbs')->insert(['first_form' => 'misdeal', 'second_form' => 'misdealt', 'third_form' => 'misdealt', 'translate' => 'поступать неправильно']);
        DB::table('verbs')->insert(['first_form' => 'misgive', 'second_form' => 'misgave', 'third_form' => 'misgiven', 'translate' => 'внушать опасения']);
        DB::table('verbs')->insert(['first_form' => 'mishear', 'second_form' => 'misheard', 'third_form' => 'misheard', 'translate' => 'ослышаться']);
        DB::table('verbs')->insert(['first_form' => 'mishit', 'second_form' => 'mishit', 'third_form' => 'mishit', 'translate' => 'промахнуться']);
        DB::table('verbs')->insert(['first_form' => 'mislay', 'second_form' => 'mislaid', 'third_form' => 'mislaid', 'translate' => 'класть не на место']);
        DB::table('verbs')->insert(['first_form' => 'mislead', 'second_form' => 'misled', 'third_form' => 'misled', 'translate' => 'ввести в заблуждение']);
        DB::table('verbs')->insert(['first_form' => 'misread', 'second_form' => 'misread', 'third_form' => 'misread', 'translate' => 'неправильно истолковывать']);
        DB::table('verbs')->insert(['first_form' => 'misspell', 'second_form' => 'misspelt; misspeled', 'third_form' => 'misspelt; misspeled', 'translate' => 'писать с ошибками']);
        DB::table('verbs')->insert(['first_form' => 'misspend', 'second_form' => 'misspent', 'third_form' => 'misspent', 'translate' => 'экономить']);
        DB::table('verbs')->insert(['first_form' => 'mistake', 'second_form' => 'mistook', 'third_form' => 'mistaken', 'translate' => 'неправильно понимать']);
        DB::table('verbs')->insert(['first_form' => 'misunderstand', 'second_form' => 'misunderstood', 'third_form' => 'misunderstood', 'translate' => 'неправильно понимать']);
        DB::table('verbs')->insert(['first_form' => 'mow', 'second_form' => 'mowed', 'third_form' => 'mown; mowed', 'translate' => 'косить']);
        DB::table('verbs')->insert(['first_form' => 'outbid', 'second_form' => 'outbid', 'third_form' => 'outbid', 'translate' => 'перебивать цену']);
        DB::table('verbs')->insert(['first_form' => 'outdo', 'second_form' => 'outdid', 'third_form' => 'outdone', 'translate' => 'превосходить']);
        DB::table('verbs')->insert(['first_form' => 'outfight', 'second_form' => 'outfought', 'third_form' => 'outfought', 'translate' => 'побеждать (в бою)']);
        DB::table('verbs')->insert(['first_form' => 'outgrow', 'second_form' => 'outgrew', 'third_form' => 'outgrown', 'translate' => 'вырастать из']);
        DB::table('verbs')->insert(['first_form' => 'output', 'second_form' => 'output; outputted', 'third_form' => 'output; outputted', 'translate' => 'выходить']);
        DB::table('verbs')->insert(['first_form' => 'outrun', 'second_form' => 'outran', 'third_form' => 'outrun', 'translate' => 'перегонять; опережать']);
        DB::table('verbs')->insert(['first_form' => 'outsell', 'second_form' => 'outsold', 'third_form' => 'outsold', 'translate' => 'продавать лучше или дороже']);
        DB::table('verbs')->insert(['first_form' => 'outshine', 'second_form' => 'outshone', 'third_form' => 'outshone', 'translate' => 'затмевать']);
        DB::table('verbs')->insert(['first_form' => 'overbid', 'second_form' => 'overbid', 'third_form' => 'overbid', 'translate' => 'повелевать']);
        DB::table('verbs')->insert(['first_form' => 'overcome', 'second_form' => 'overcame', 'third_form' => 'overcome', 'translate' => 'компенсировать']);
        DB::table('verbs')->insert(['first_form' => 'overdo', 'second_form' => 'overdid', 'third_form' => 'overdone', 'translate' => 'пережари(ва)ть']);
        DB::table('verbs')->insert(['first_form' => 'overdraw', 'second_form' => 'overdrew', 'third_form' => 'overdrawn', 'translate' => 'превышать']);
        DB::table('verbs')->insert(['first_form' => 'overeat', 'second_form' => 'overate', 'third_form' => 'overeaten', 'translate' => 'объедаться']);
        DB::table('verbs')->insert(['first_form' => 'overfly', 'second_form' => 'overflew', 'third_form' => 'overflown', 'translate' => 'перелетать']);
        DB::table('verbs')->insert(['first_form' => 'overhang', 'second_form' => 'overhung', 'third_form' => 'overhung', 'translate' => 'нависать']);
        DB::table('verbs')->insert(['first_form' => 'overhear', 'second_form' => 'overheard', 'third_form' => 'overheard', 'translate' => 'подслуш(ив)ать']);
        DB::table('verbs')->insert(['first_form' => 'overlay', 'second_form' => 'overlaid', 'third_form' => 'overlaid', 'translate' => 'покры(ва)ть']);
        DB::table('verbs')->insert(['first_form' => 'overpay', 'second_form' => 'overpaid', 'third_form' => 'overpaid', 'translate' => 'переплачивать']);
        DB::table('verbs')->insert(['first_form' => 'override', 'second_form' => 'overrode', 'third_form' => 'overridden', 'translate' => 'отвергать; отклонять']);
        DB::table('verbs')->insert(['first_form' => 'overrun', 'second_form' => 'overran', 'third_form' => 'overrun', 'translate' => 'переливаться через край']);
        DB::table('verbs')->insert(['first_form' => 'oversee', 'second_form' => 'oversaw', 'third_form' => 'overseen', 'translate' => 'надзирать за']);
        DB::table('verbs')->insert(['first_form' => 'overshoot', 'second_form' => 'overshot', 'third_form' => 'overshot', 'translate' => 'расстрелять']);
        DB::table('verbs')->insert(['first_form' => 'oversleep', 'second_form' => 'overslept', 'third_form' => 'overslept', 'translate' => 'прос(ы)пать']);
        DB::table('verbs')->insert(['first_form' => 'overtake', 'second_form' => 'overtook', 'third_form' => 'overtaken', 'translate' => 'догонять']);
        DB::table('verbs')->insert(['first_form' => 'overthrow', 'second_form' => 'overthrew', 'third_form' => 'overthrown', 'translate' => 'свергать']);
        DB::table('verbs')->insert(['first_form' => 'partake', 'second_form' => 'partook', 'third_form' => 'partaken', 'translate' => 'принимать участие']);
        DB::table('verbs')->insert(['first_form' => 'pay', 'second_form' => 'paid', 'third_form' => 'paid', 'translate' => 'платить']);
        DB::table('verbs')->insert(['first_form' => 'plead', 'second_form' => 'pleaded; pled', 'third_form' => 'pleaded; pled', 'translate' => 'обращаться к суду']);
        DB::table('verbs')->insert(['first_form' => 'prepay', 'second_form' => 'prepaid', 'third_form' => 'prepaid', 'translate' => 'платить вперед']);
        DB::table('verbs')->insert(['first_form' => 'prove', 'second_form' => 'proved', 'third_form' => 'proved; proven', 'translate' => 'доказывать; оказаться']);
        DB::table('verbs')->insert(['first_form' => 'put', 'second_form' => 'put', 'third_form' => 'put', 'translate' => 'класть']);
        DB::table('verbs')->insert(['first_form' => 'quit', 'second_form' => 'quit; quitted', 'third_form' => 'quit; quitted', 'translate' => 'покидать; оставлять']);
        DB::table('verbs')->insert(['first_form' => 'read', 'second_form' => 'read; red', 'third_form' => 'read; red', 'translate' => 'читать']);
        DB::table('verbs')->insert(['first_form' => 'rebind', 'second_form' => 'rebound', 'third_form' => 'rebound', 'translate' => 'перевязывать']);
        DB::table('verbs')->insert(['first_form' => 'rebuild', 'second_form' => 'rebuilt', 'third_form' => 'rebuilt', 'translate' => 'перестроить']);
        DB::table('verbs')->insert(['first_form' => 'recast', 'second_form' => 'recast', 'third_form' => 'recast', 'translate' => 'видоизменять; преобразовывать']);
        DB::table('verbs')->insert(['first_form' => 'redo', 'second_form' => 'redid', 'third_form' => 'redone', 'translate' => 'повторять сделанное']);
        DB::table('verbs')->insert(['first_form' => 'rehear', 'second_form' => 'reheard', 'third_form' => 'reheard', 'translate' => 'слушать вторично']);
        DB::table('verbs')->insert(['first_form' => 'remake', 'second_form' => 'remade', 'third_form' => 'remade', 'translate' => 'переделывать']);
        DB::table('verbs')->insert(['first_form' => 'rend', 'second_form' => 'rent', 'third_form' => 'rent', 'translate' => 'раздирать']);
        DB::table('verbs')->insert(['first_form' => 'repay', 'second_form' => 'repaid', 'third_form' => 'repaid', 'translate' => 'отдавать долг']);
        DB::table('verbs')->insert(['first_form' => 'rerun', 'second_form' => 'reran', 'third_form' => 'rerun', 'translate' => 'выполнять повторно']);
        DB::table('verbs')->insert(['first_form' => 'resell', 'second_form' => 'resold', 'third_form' => 'resold', 'translate' => 'перепродавать']);
        DB::table('verbs')->insert(['first_form' => 'reset', 'second_form' => 'reset', 'third_form' => 'reset', 'translate' => 'возвращать']);
        DB::table('verbs')->insert(['first_form' => 'resit', 'second_form' => 'resat', 'third_form' => 'resat', 'translate' => 'пересиживать']);
        DB::table('verbs')->insert(['first_form' => 'retake', 'second_form' => 'retook', 'third_form' => 'retaken', 'translate' => 'забирать']);
        DB::table('verbs')->insert(['first_form' => 'retell', 'second_form' => 'retold', 'third_form' => 'retold', 'translate' => 'пересказывать']);
        DB::table('verbs')->insert(['first_form' => 'rewrite', 'second_form' => 'rewrote', 'third_form' => 'rewritten', 'translate' => 'пере(за)писать']);
        DB::table('verbs')->insert(['first_form' => 'rid', 'second_form' => 'rid; ridded', 'third_form' => 'rid; ridded', 'translate' => 'избавлять']);
        DB::table('verbs')->insert(['first_form' => 'ride', 'second_form' => 'rode', 'third_form' => 'ridden', 'translate' => 'ездить верхом']);
        DB::table('verbs')->insert(['first_form' => 'ring', 'second_form' => 'rang', 'third_form' => 'rung', 'translate' => 'звонить']);
        DB::table('verbs')->insert(['first_form' => 'rise', 'second_form' => 'rose', 'third_form' => 'risen', 'translate' => 'подняться']);
        DB::table('verbs')->insert(['first_form' => 'rive', 'second_form' => 'rived', 'third_form' => 'riven', 'translate' => 'расщеплять']);
        DB::table('verbs')->insert(['first_form' => 'run', 'second_form' => 'ran', 'third_form' => 'run', 'translate' => 'бежать; течь']);
        DB::table('verbs')->insert(['first_form' => 'saw', 'second_form' => 'sawed', 'third_form' => 'sawn; sawed', 'translate' => 'пилить']);
        DB::table('verbs')->insert(['first_form' => 'say', 'second_form' => 'said', 'third_form' => 'said', 'translate' => 'говорить; сказать']);
        DB::table('verbs')->insert(['first_form' => 'see', 'second_form' => 'saw', 'third_form' => 'seen', 'translate' => 'видеть']);
        DB::table('verbs')->insert(['first_form' => 'seek', 'second_form' => 'sought', 'third_form' => 'sought', 'translate' => 'искать']);
        DB::table('verbs')->insert(['first_form' => 'sell', 'second_form' => 'sold', 'third_form' => 'sold', 'translate' => 'продавать']);
        DB::table('verbs')->insert(['first_form' => 'send', 'second_form' => 'sent', 'third_form' => 'sent', 'translate' => 'послать']);
        DB::table('verbs')->insert(['first_form' => 'set', 'second_form' => 'set', 'third_form' => 'set', 'translate' => 'устанавливать']);
        DB::table('verbs')->insert(['first_form' => 'sew', 'second_form' => 'sewed', 'third_form' => 'sewed; sewn', 'translate' => 'шить']);
        DB::table('verbs')->insert(['first_form' => 'shake', 'second_form' => 'shook', 'third_form' => 'shaken', 'translate' => 'трясти']);
        DB::table('verbs')->insert(['first_form' => 'shave', 'second_form' => 'shaved', 'third_form' => 'shaved; shaven', 'translate' => 'брить(ся)']);
        DB::table('verbs')->insert(['first_form' => 'shear', 'second_form' => 'sheared', 'third_form' => 'shorn; sheared', 'translate' => 'стричь']);
        DB::table('verbs')->insert(['first_form' => 'shed', 'second_form' => 'shed', 'third_form' => 'shed', 'translate' => 'проливать']);
        DB::table('verbs')->insert(['first_form' => 'shine', 'second_form' => 'shone; shined', 'third_form' => 'shone; shined', 'translate' => 'светить; сиять']);
        DB::table('verbs')->insert(['first_form' => 'shoe', 'second_form' => 'shod', 'third_form' => 'shod', 'translate' => 'обувать; подковывать']);
        DB::table('verbs')->insert(['first_form' => 'shoot', 'second_form' => 'shot', 'third_form' => 'shot', 'translate' => 'стрелять; давать побеги']);
        DB::table('verbs')->insert(['first_form' => 'show', 'second_form' => 'showed', 'third_form' => 'shown; showed', 'translate' => 'показывать']);
        DB::table('verbs')->insert(['first_form' => 'shred', 'second_form' => 'shred; shredded', 'third_form' => 'shred; shredded', 'translate' => 'кромсать; расползаться']);
        DB::table('verbs')->insert(['first_form' => 'shrink', 'second_form' => 'shrank; shrunk', 'third_form' => 'shrunk', 'translate' => 'сокращаться; сжиматься; отпрянуть']);
        DB::table('verbs')->insert(['first_form' => 'shrive', 'second_form' => 'shrove; shrived', 'third_form' => 'shriven; shrived', 'translate' => 'исповедовать']);
        DB::table('verbs')->insert(['first_form' => 'shut', 'second_form' => 'shut', 'third_form' => 'shut', 'translate' => 'закрывать']);
        DB::table('verbs')->insert(['first_form' => 'sing', 'second_form' => 'sang', 'third_form' => 'sung', 'translate' => 'петь']);
        DB::table('verbs')->insert(['first_form' => 'sink', 'second_form' => 'sank', 'third_form' => 'sunk', 'translate' => 'опускаться; погружаться; тонуть']);
        DB::table('verbs')->insert(['first_form' => 'sit', 'second_form' => 'sat', 'third_form' => 'sat', 'translate' => 'сидеть']);
        DB::table('verbs')->insert(['first_form' => 'slay', 'second_form' => 'slew', 'third_form' => 'slain', 'translate' => 'убивать']);
        DB::table('verbs')->insert(['first_form' => 'sleep', 'second_form' => 'slept', 'third_form' => 'slept', 'translate' => 'спать']);
        DB::table('verbs')->insert(['first_form' => 'slide', 'second_form' => 'slid', 'third_form' => 'slid', 'translate' => 'скользить']);
        DB::table('verbs')->insert(['first_form' => 'sling', 'second_form' => 'slung', 'third_form' => 'slung', 'translate' => 'швырять; подвешивать']);
        DB::table('verbs')->insert(['first_form' => 'slink', 'second_form' => 'slunk', 'third_form' => 'slunk', 'translate' => 'идти крадучись']);
        DB::table('verbs')->insert(['first_form' => 'slit', 'second_form' => 'slit', 'third_form' => 'slit', 'translate' => 'раздирать(ся); разрезать (вдоль)']);
        DB::table('verbs')->insert(['first_form' => 'smell', 'second_form' => 'smelt; smelled', 'third_form' => 'smelt; smelled', 'translate' => 'пахнуть; нюхать']);
        DB::table('verbs')->insert(['first_form' => 'smite', 'second_form' => 'smote', 'third_form' => 'smitten', 'translate' => 'ударять; разбивать']);
        DB::table('verbs')->insert(['first_form' => 'sow', 'second_form' => 'sowed', 'third_form' => 'sowed; sown', 'translate' => '(по)сеять']);
        DB::table('verbs')->insert(['first_form' => 'speak', 'second_form' => 'spoke', 'third_form' => 'spoken', 'translate' => 'говорить']);
        DB::table('verbs')->insert(['first_form' => 'speed', 'second_form' => 'sped; speeded', 'third_form' => 'sped; speeded', 'translate' => 'ускорять; спешить']);
        DB::table('verbs')->insert(['first_form' => 'spell', 'second_form' => 'spelt; spelled', 'third_form' => 'spell; spelled', 'translate' => 'писать или читать по буквам']);
        DB::table('verbs')->insert(['first_form' => 'spend', 'second_form' => 'spent', 'third_form' => 'spent', 'translate' => 'тратить']);
        DB::table('verbs')->insert(['first_form' => 'spill', 'second_form' => 'spilt; spilled', 'third_form' => 'spilt; spilled', 'translate' => 'пролить']);
        DB::table('verbs')->insert(['first_form' => 'spin', 'second_form' => 'spun; span', 'third_form' => 'spun', 'translate' => 'прясть']);
        DB::table('verbs')->insert(['first_form' => 'spit', 'second_form' => 'spat; spit', 'third_form' => 'spat; spit', 'translate' => 'плевать']);
        DB::table('verbs')->insert(['first_form' => 'split', 'second_form' => 'split', 'third_form' => 'split', 'translate' => 'расщепить(ся)']);
        DB::table('verbs')->insert(['first_form' => 'spoil', 'second_form' => 'spoilt; spoiled', 'third_form' => 'spoilt; spoiled', 'translate' => 'портить']);
        DB::table('verbs')->insert(['first_form' => 'spotlight', 'second_form' => 'spotlit; spotlighted', 'third_form' => 'spotlit; spotlighted', 'translate' => 'осветить']);
        DB::table('verbs')->insert(['first_form' => 'spread', 'second_form' => 'spread', 'third_form' => 'spread', 'translate' => 'распространиться']);
        DB::table('verbs')->insert(['first_form' => 'spring', 'second_form' => 'sprang', 'third_form' => 'sprung', 'translate' => 'вскочить; возникнуть']);
        DB::table('verbs')->insert(['first_form' => 'stand', 'second_form' => 'stood', 'third_form' => 'stood', 'translate' => 'стоять']);
        DB::table('verbs')->insert(['first_form' => 'stave', 'second_form' => 'staved; stove', 'third_form' => 'staved; stove', 'translate' => 'проламывать; разби(ва)ть']);
        DB::table('verbs')->insert(['first_form' => 'steal', 'second_form' => 'stole', 'third_form' => 'stolen', 'translate' => 'украсть']);
        DB::table('verbs')->insert(['first_form' => 'stick', 'second_form' => 'stuck', 'third_form' => 'stuck', 'translate' => 'уколоть; приклеить']);
        DB::table('verbs')->insert(['first_form' => 'sting', 'second_form' => 'stung', 'third_form' => 'stung', 'translate' => 'ужалить']);
        DB::table('verbs')->insert(['first_form' => 'stink', 'second_form' => 'stank; stunk', 'third_form' => 'stunk', 'translate' => 'вонять']);
        DB::table('verbs')->insert(['first_form' => 'strew', 'second_form' => 'strewed', 'third_form' => 'strewn; strewed', 'translate' => 'усеять; устлать']);
        DB::table('verbs')->insert(['first_form' => 'stride', 'second_form' => 'strode', 'third_form' => 'stridden', 'translate' => 'шагать']);
        DB::table('verbs')->insert(['first_form' => 'strike', 'second_form' => 'struck', 'third_form' => 'struck', 'translate' => 'ударить; бить; бастовать']);
        DB::table('verbs')->insert(['first_form' => 'string', 'second_form' => 'strung', 'third_form' => 'strung', 'translate' => 'нанизать; натянуть']);
        DB::table('verbs')->insert(['first_form' => 'strive', 'second_form' => 'strove', 'third_form' => 'striven', 'translate' => 'стараться']);
        DB::table('verbs')->insert(['first_form' => 'sublet', 'second_form' => 'sublet', 'third_form' => 'sublet', 'translate' => 'передавать в субаренду']);
        DB::table('verbs')->insert(['first_form' => 'swear', 'second_form' => 'swore', 'third_form' => 'sworn', 'translate' => '(по)клясться; присягнуть']);
        DB::table('verbs')->insert(['first_form' => 'sweep', 'second_form' => 'swept', 'third_form' => 'swept', 'translate' => 'мести; промчаться']);
        DB::table('verbs')->insert(['first_form' => 'swell', 'second_form' => 'swelled', 'third_form' => 'swollen; swelled', 'translate' => 'вздуться']);
        DB::table('verbs')->insert(['first_form' => 'swim', 'second_form' => 'swam', 'third_form' => 'swum', 'translate' => 'плыть']);
        DB::table('verbs')->insert(['first_form' => 'swing', 'second_form' => 'swung', 'third_form' => 'swung', 'translate' => 'качаться']);
        DB::table('verbs')->insert(['first_form' => 'take', 'second_form' => 'took', 'third_form' => 'taken', 'translate' => 'взять; брать']);
        DB::table('verbs')->insert(['first_form' => 'teach', 'second_form' => 'taught', 'third_form' => 'taught', 'translate' => 'учить']);
        DB::table('verbs')->insert(['first_form' => 'tear', 'second_form' => 'tore', 'third_form' => 'torn', 'translate' => 'рвать']);
        DB::table('verbs')->insert(['first_form' => 'tell', 'second_form' => 'told', 'third_form' => 'told', 'translate' => 'рассказывать; сказать']);
        DB::table('verbs')->insert(['first_form' => 'think', 'second_form' => 'thought', 'third_form' => 'thought', 'translate' => 'думать']);
        DB::table('verbs')->insert(['first_form' => 'thrive', 'second_form' => 'throve; trived', 'third_form' => 'thriven; trived', 'translate' => 'процветать']);
        DB::table('verbs')->insert(['first_form' => 'throw', 'second_form' => 'threw', 'third_form' => 'thrown', 'translate' => 'бросить']);
        DB::table('verbs')->insert(['first_form' => 'thrust', 'second_form' => 'thrust', 'third_form' => 'thrust', 'translate' => 'толкнуть; сунуть']);
        DB::table('verbs')->insert(['first_form' => 'tread', 'second_form' => 'trod', 'third_form' => 'trod; trodden', 'translate' => 'ступать']);
        DB::table('verbs')->insert(['first_form' => 'unbend', 'second_form' => 'unbent', 'third_form' => 'unbent', 'translate' => 'разогнуть(ся)']);
        DB::table('verbs')->insert(['first_form' => 'underbid', 'second_form' => 'underbid', 'third_form' => 'underbid', 'translate' => 'снижать цену']);
        DB::table('verbs')->insert(['first_form' => 'undercut', 'second_form' => 'undercut', 'third_form' => 'undercut', 'translate' => 'сбивать цены']);
        DB::table('verbs')->insert(['first_form' => 'undergo', 'second_form' => 'underwent', 'third_form' => 'undergone', 'translate' => 'проходить; подвергаться']);
        DB::table('verbs')->insert(['first_form' => 'underlie', 'second_form' => 'underlay', 'third_form' => 'underlain', 'translate' => 'лежать в основе']);
        DB::table('verbs')->insert(['first_form' => 'underpay', 'second_form' => 'underpaid', 'third_form' => 'underpaid', 'translate' => 'оплачивать слишком низко']);
        DB::table('verbs')->insert(['first_form' => 'undersell', 'second_form' => 'undersold', 'third_form' => 'undersold', 'translate' => 'продавать дешевле']);
        DB::table('verbs')->insert(['first_form' => 'understand', 'second_form' => 'understood', 'third_form' => 'understood', 'translate' => 'понимать']);
        DB::table('verbs')->insert(['first_form' => 'undertake', 'second_form' => 'undertook', 'third_form' => 'undertaken', 'translate' => 'предпринять']);
        DB::table('verbs')->insert(['first_form' => 'underwrite', 'second_form' => 'underwrote', 'third_form' => 'underwritten', 'translate' => 'подписыва(ть)ся']);
        DB::table('verbs')->insert(['first_form' => 'undo', 'second_form' => 'undid', 'third_form' => 'undone', 'translate' => 'уничтожать сделанное']);
        DB::table('verbs')->insert(['first_form' => 'unfreeze', 'second_form' => 'unfroze', 'third_form' => 'unfrozen', 'translate' => 'размораживать']);
        DB::table('verbs')->insert(['first_form' => 'unsay', 'second_form' => 'unsaid', 'third_form' => 'unsaid', 'translate' => 'брать назад свои слова']);
        DB::table('verbs')->insert(['first_form' => 'unwind', 'second_form' => 'unwound', 'third_form' => 'unwound', 'translate' => 'развертывать']);
        DB::table('verbs')->insert(['first_form' => 'uphold', 'second_form' => 'upheld', 'third_form' => 'upheld', 'translate' => 'поддерживать']);
        DB::table('verbs')->insert(['first_form' => 'upset', 'second_form' => 'upset', 'third_form' => 'upset', 'translate' => 'опрокинуть(ся)']);
        DB::table('verbs')->insert(['first_form' => 'wake', 'second_form' => 'woke; waked', 'third_form' => 'woken; waked', 'translate' => 'просыпаться; будить']);
        DB::table('verbs')->insert(['first_form' => 'waylay', 'second_form' => 'waylaid', 'third_form' => 'waylaid', 'translate' => 'подстерегать']);
        DB::table('verbs')->insert(['first_form' => 'wear', 'second_form' => 'wore', 'third_form' => 'worn', 'translate' => 'носить(одежду)']);
        DB::table('verbs')->insert(['first_form' => 'weave', 'second_form' => 'wove; weaved', 'third_form' => 'woven; weaved', 'translate' => 'ткать']);
        DB::table('verbs')->insert(['first_form' => 'wed', 'second_form' => 'wed; wedded', 'third_form' => 'wed; wedded', 'translate' => 'выдавать замуж']);
        DB::table('verbs')->insert(['first_form' => 'weep', 'second_form' => 'wept', 'third_form' => 'wept', 'translate' => 'плакать']);
        DB::table('verbs')->insert(['first_form' => 'wet', 'second_form' => 'wet; wetted', 'third_form' => 'wet; wetted', 'translate' => 'мочить; увлажнять']);
        DB::table('verbs')->insert(['first_form' => 'win', 'second_form' => 'won', 'third_form' => 'won', 'translate' => 'выиграть']);
        DB::table('verbs')->insert(['first_form' => 'wind', 'second_form' => 'wound', 'third_form' => 'wound', 'translate' => 'заводить (механизм)']);
        DB::table('verbs')->insert(['first_form' => 'withdraw', 'second_form' => 'withdrew', 'third_form' => 'withdrawn', 'translate' => 'взять назад; отозвать']);
        DB::table('verbs')->insert(['first_form' => 'withhold', 'second_form' => 'withheld', 'third_form' => 'withheld', 'translate' => 'удерживать']);
        DB::table('verbs')->insert(['first_form' => 'withstand', 'second_form' => 'withstood', 'third_form' => 'withstood', 'translate' => 'противиться']);
        DB::table('verbs')->insert(['first_form' => 'work', 'second_form' => 'worked; wrought', 'third_form' => 'worked; wrought', 'translate' => 'работать']);
        DB::table('verbs')->insert(['first_form' => 'wring', 'second_form' => 'wrung', 'third_form' => 'wrung', 'translate' => 'скрутить; сжать']);
        DB::table('verbs')->insert(['first_form' => 'write', 'second_form' => 'wrote', 'third_form' => 'written', 'translate' => 'писать']);
    }
}
